# Generated by Django 5.2.16 on 2026-07-14 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('cpu_usage_avg', models.FloatField()),
                ('cpu_usage_max', models.FloatField()),
                ('cpu_usage_min', models.FloatField()),
                ('ram_usage_avg', models.FloatField()),
                ('ram_usage_min', models.FloatField()),
                ('ram_usage_max', models.FloatField()),
                ('disk_used', models.BigIntegerField()),
            ],
        ),
    ]
